### PR TITLE
Simplify installation page

### PR DESCRIPTION
**Pull request by thieman**
@jsingle This page needs to be as simple and not-scary as possible

### CODE REVIEW

**Comment by jsingle** [comment]
OK - I feel like somewhere we should document that our install script sets up a plist at such and such a location.  Could that go in a subsection under this copy?

**Comment by thieman** [comment]
It's the standard (only?) way to define services in OS X, and the install script itself is super small and easy to reason about. I don't think we need to detail the installation at that level.

**Comment by thieman** [comment]
Docker Compose didn't see a reason to https://docs.docker.com/compose/install/

**Comment by jsingle** [comment]
I don't think docker-compose sets up a service for you.  There are multiple file paths that you can place your plist at.  But i agree the installation is easy to reason about

**Comment by thieman** [comment]
Oh, right, derp. Point still stands, a lot of things you `apt-get` install will install services and they're not going to go out of their way to detail how that's done.

**Pull request merged**
