### PR TITLE
provide strs to execv

### PR DESCRIPTION
**Pull request by zacharym**
@jsingle this was breaking for me locally .. not sure if I'm doing something else stupidly locally
cc @thieman

### CODE REVIEW

**Comment by jsingle** [comment]
Certainly won't hurt anything, I'm definitely curious as to why you were seeing this (but not others)

**Comment by thieman** [comment]
-1 fix the actual problem

**Comment by jsingle** [comment]
Yeah there's an inconsistency in the different ways we're setting the `vm_memory_size` field.  The fix isn't just to cast to a string here

**Comment by zacharym** [comment]
Yeah, this was more just a convenient way to share information, not what I thought the actual fix would be.

**Pull request closed without merging**
