### PR TITLE
Touch up contributing docs

### PR DESCRIPTION
**Pull request by thieman**
@zacharym @paetling 

image

### CODE REVIEW

**Comment by thieman** [comment]
Also got rid of RYE in README

**Comment by paetling** [comment]
We are no longer giving out a link with the most recent version.  We no longer want to do that?

**Comment by thieman** [comment]
We still have that link, it's just in the docs. Our README and product page both point to it.

**Comment by paetling** [comment]
:ghost: :cow:

**Comment by zacharym** [comment]
:ghost: :camel: > :ghost: :cow:

**Comment by jsingle** [comment]
:+1: for :camel:

**Pull request merged**
