### PR TITLE
Make the restore command append backup dir if not provided

### LINKED ISSUE #632: Restore command is unintuitive
It makes sense to me as a user for the `backup` and `restore` commands to take basically the same arguments. I expect this to work:

```
dusty disk backup /tmp/backup
dusty disk restore /tmp/backup
```

However, currently the correct usage requires you to point `restore` to the folder that Dusty makes inside the directory you give it (we do this to minimize the chances that we overwrite anything we shouldn't):

```
dusty disk backup /tmp/backup
dusty disk restore /tmp/backup/dusty-backup
```

### PR DESCRIPTION
**Pull request by thieman**
@paetling Fixes #632.

### CODE REVIEW

**Comment by paetling** [comment]
What is the reason to even still allow full specification to the directory?   Just to maintain backwards compatibility.  Seems like the syntax for backup and restore being the same is what we want, and anything else might just add confusion.

**Comment by thieman** [comment]
Backwards compatibility is the main reason, plus allowing both makes the command as "do what I mean" as possible

**Comment by paetling** [comment]
Ehh.  Looking at how the command works now, I hate that we make people specify the local_back_dir in the path.  The reasons i hate it are 1. inconsistency that you mention  2. We expose dusty internals to the user.   If we just implement your change we fix 1 and keep backwards compatibility, but continue to suffer from 2.  I think It allows us more flexibility and can lead to less confusion if we always look for local_back_dir for them.

**Comment by paetling** [comment]
:ghost: :cow:

**Pull request merged**
