### PR TITLE
Move plist install dir to /Library/LaunchDaemons

### LINKED ISSUE #402: Installation not working with OSX 10.11 (El Capitan)
Seems El Capitan disallow writing in ```/System/Library/LaunchDaemons```
Not really tested, but install works with this script:

```bash
set -e

# This is set by Jenkins during release
release='0.2.1'

function bold_echo {
    echo -e "\033[1m$1\033[0m"
}

bold_echo "Downloading dusty binary"
curl -L https://github.com/gamechanger/dusty/releases/download/$release/dusty > /usr/local/bin/dusty
chmod +x /usr/local/bin/dusty
bold_echo "Authenticating as super user... needed to setup daemon"
bold_echo "Resetting dusty daemon"
curl -L -o ~/Library/LaunchAgents/org.gamechanger.dusty.plist https://raw.githubusercontent.com/gamechanger/dusty/$release/setup/org.gamechanger.dusty.plist
launchctl unload ~/Library/LaunchAgents/org.gamechanger.dusty.plist
bold_echo "Testing dusty daemon's preflight..."
sudo -H dusty -d --preflight-only || (bold_echo "Preflight failed; not loading daemon"; exit 1)
bold_echo "Loading dusty daemon"
launchctl load ~/Library/LaunchAgents/org.gamechanger.dusty.plist
````

### PR DESCRIPTION
**Pull request by thieman**
@jsingle Fixes #402. Also cleans up existing plist install location.

### CODE REVIEW

**Comment by jsingle** [comment]
Can we change it from org to com?  while we're doing this

**Comment by thieman** [comment]
Fo sho yo

**Comment by thieman** [comment]
We'll need to make sure we test this properly with our next RC

**Comment by thieman** [comment]
Gonna add some changelog stuff too, actually.

**Comment by thieman** [comment]
@jsingle Review

**Comment by jsingle** [comment]
Looks good to me :rocket:

**Pull request merged**
