### PR TITLE
Js refactor demote

### PR DESCRIPTION
**Pull request by jsingle**
@paetling the goal here is to make more general functions, as we'll sometimes want to run this stuff without actually demoting

### CODE REVIEW

**Comment by jsingle** [comment]
I guess we should call the module something besides "demote" - suggestions?

**Comment by paetling** [comment]
subprocess?

**Comment by paetling** [comment]
:ghost: :cow: This looks good

**Comment by jsingle** [comment]
Ugh I don't want to call it subprocess and have to deal with import conflicts

**Comment by paetling** [comment]
subcommand

**Comment by paetling** [comment]
child_command

**Comment by paetling** [comment]
child_process

**Comment by paetling** [comment]
child_process

**Comment by jsingle** [comment]
Well I just did subprocess. If sorting out conflicts is a pain I'll select another suggestion

**Pull request merged**
