### PR TITLE
Js colons fix for volumes

### PR DESCRIPTION
**Pull request by jsingle**
@thieman Docker Compose parses `volumes` by splitting on colons.  Having colons in a local path will mess that up

Fixes https://github.com/gamechanger/dusty/issues/459

### CODE REVIEW

**Comment by thieman** [comment]
There's no way around this? Is there an issue in Compose?

**Comment by jsingle** [comment]
I haven't found anything.  If you think this is really messy I can look a bit more, but I don't think this is that bad...

**Comment by thieman** [comment]
Uuuuuuugh ok. It's just a lot of janky code to deal with a corner case. How did we even find this bug? Are people actually using colons in repo names / directories? Those people are dumb

**Comment by jsingle** [comment]
I found it because when you specify https://github/blah, the local path contains a folder called https://github/blah, and docker-compose breaks.  So at the very least, we need to handle the case where people enter ssh: or http: as part of the path.  There might be a slightly cleaner way to do that particular thing, but the colons are allowed in filepaths anyway, so I thought I might as well make a more general check

**Comment by thieman** [comment]
:bear:

**Pull request merged**
